### ISSUE TITLE
 AttributeError: 'G' object has no attribute 'landmarks'

### ISSUE THREAD

**Issue by molo32** [YotamNitzan/ID-disentanglement#6] opened 2021-02-12 17:04 UTC
```
!python test.py molo2 --pretrained_models_path "/content/ID-disentanglement/stylegan_G_256x256_synthesis/" \
    --load_checkpoint "/content/drive/MyDrive/checkpoint" \
    --input_dir "/content/id" \
    --output_dir "/content/out" \
    --test_func interpolate
```

```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:2281: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '
Wrong data format for .ipynb_checkpoints
Traceback (most recent call last):
  File "test.py", line 45, in <module>
    main()
  File "test.py", line 41, in main
    test_func()
  File "/content/ID-disentanglement/inference.py", line 115, in interpolate
    const_img = self.G(const_img, const_img)[0]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3887, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /content/ID-disentanglement/model/generator.py:42 call  *
        lnds = self.landmarks(x2)

    AttributeError: 'G' object has no attribute 'landmarks'
```

**Comment by minha12** [comment] 2021-03-02 11:59
Same issue, is there any fix yet?

**Comment by NTU-P04922004** [comment] 2021-03-11 08:14
The issue is due to the ```landmarks``` attribute is not instantiated properly when in test mode (the ```train``` flag is ```False```). A quick workaround to the issue is to set the ```lnds``` variable to ```None``` in the ```call``` method.
```python
# lnds = self.landmarks(x2)
lnds = None
```

**Comment by YotamNitzan** [comment] 2021-03-15 15:16
Hi,
As @NTU-P04922004  suggested, indeed in test mode the landmarks network should not be called. I have pushed a fix.

**Closed as completed by YotamNitzan** 2021-03-15 15:16 UTC
